imports:
  - { resource: ./common.yml }

services:
  # Grid services
  lkinteractive.lkstockemailalerts.grid.definition.factory.alerts:
    class: 'LkInteractive\Back\LkStockEmailAlerts\Grid\AlertsGridDefinitionFactory'
    parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'

  lkinteractive.lkstockemailalerts.grid.query_builder.alerts:
    class: 'LkInteractive\Back\LkStockEmailAlerts\Grid\AlertsQueryBuilder'
    parent: 'prestashop.core.grid.abstract_query_builder'
    public: true
    arguments:
      - '@prestashop.core.query.doctrine_search_criteria_applicator'
      - "@=service('prestashop.adapter.legacy.context').getContext().language.id"

  lkinteractive.lkstockemailalerts.grid.data_provider.alerts:
    class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
    arguments:
      - '@lkinteractive.lkstockemailalerts.grid.query_builder.alerts'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'alerts'

  lkinteractive.lkstockemailalerts.grid.factory.alerts :
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    arguments:
      - '@lkinteractive.lkstockemailalerts.grid.definition.factory.alerts'
      - '@lkinteractive.lkstockemailalerts.grid.data_provider.alerts'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'

  lkinteractive.lkstockemailalerts.grid.definition.factory.alert:
    class: 'LkInteractive\Back\LkStockEmailAlerts\Grid\AlertGridDefinitionFactory'
    parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'

  lkinteractive.lkstockemailalerts.grid.query_builder.alert:
    class: 'LkInteractive\Back\LkStockEmailAlerts\Grid\AlertQueryBuilder'
    parent: 'prestashop.core.grid.abstract_query_builder'
    public: true
    arguments:
      - '@prestashop.core.query.doctrine_search_criteria_applicator'
      - "@=service('prestashop.adapter.legacy.context').getContext().language.id"

  lkinteractive.lkstockemailalerts.grid.data_provider.alert:
    class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
    arguments:
      - '@lkinteractive.lkstockemailalerts.grid.query_builder.alert'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'alerts'

  lkinteractive.lkstockemailalerts.grid.factory.alert :
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    arguments:
      - '@lkinteractive.lkstockemailalerts.grid.definition.factory.alert'
      - '@lkinteractive.lkstockemailalerts.grid.data_provider.alert'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'
